[package]
name = "docbase-cli"
version = "0.1.0"
authors = ["Pocket7878 <poketo7878@gmail.com>"]
description = "Docbase.io client"
readme = "README.md"
repositry = "https://github.com/pocket7878/docbase_cli"
licence = "Apache-2.0"

[dependencies]
hyper = "*"
rustc-serialize = "0.3"
tempfile = "2.1.4"
getopts = "0.2"
